version: '3.8'

services:
  server:
    build: .
    image: mira-converse-server
    container_name: mira-server
    restart: unless-stopped
    ports:
      - "${WEBSOCKET_PORT:-8765}:8765"
    environment:
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=${WEBSOCKET_PORT:-8765}
      - WEBSOCKET_API_SECRET_KEY=${WEBSOCKET_API_SECRET_KEY:-mira}
      - WHISPER_PATH=/models/whisper
      - KOKORO_PATH=/models/kokoro
      - KOKORO_VOICE_NAME=${KOKORO_VOICE_NAME:-af_heart}
    volumes:
      - ${WHISPER_PATH:-./models/whisper}:/models/whisper
      - ${KOKORO_PATH:-./models/kokoro}:/models/kokoro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
